// ============================================================
//  Nuxt Virtual Module Type Declarations (Qodana / IDE)
//
//  These modules are auto-generated by Nuxt at build time
//  but IDEs need explicit .d.ts stubs for type-checking.
// ============================================================

declare module '#app' {
  export function useNuxtApp(): any
  export function useRouter(): any
  export function useRoute(): any
  export const navigateTo: any
  export function useRuntimeConfig(): any
  export function useState<T = any>(key: string, init?: () => T): import('vue').Ref<T>
  export function useFetch<T = any>(url: string, opts?: any): Promise<any>
  export function useAsyncData<T = any>(key: string, handler: (...args: any[]) => Promise<T>, options?: any): any
  export function defineNuxtComponent(options: any): any
}

declare module '#imports' {
  export { useI18n } from '../composables/useLocale'
  export { useApiKey, ApiKeys } from '../composables/useApiKey'
}

declare module '#app/nuxt' {
  export * from '#app'
}
